# ----------------------------------------------------------------------------
#
# Package             : okhttp
# Source Repo         : https://github.com/square/okhttp
# Travis Job Link     : https://travis-ci.com/github/asellappen/okhttp/
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
sudo: required

language: java

jdk: 
  - openjdk8
  - openjdk11
  - openjdk16
  
matrix:
  include:
   - arch: ppc64le 
     dist: xenial
   - arch: ppc64le 
     dist: bionic
   - arch: ppc64le 
     dist: focal

script :
   -  ./gradlew build 
   -  ./gradlew clean test  --rerun-tasks 
