# ----------------------------------------------------------------------------
#
# Package             : okhttp
# Source Repo         : https://github.com/square/okhttp
# Travis Job Link     : https://travis-ci.com/github/asellappen/okhttp/
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
dist: xenial

language: java

jdk: openjdk11

matrix:
  include:
   - arch: amd64 
     os: linux
     dist: xenial

   - arch: ppc64le 
     os: linux
     dist: xenial

before_install:
   - if [ "$TRAVIS_CPU_ARCH" = "ppc64le" ]; then
       sudo wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add - ;
       sudo add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ ;
       sudo rm -rf /var/lib/apt/lists/* ;
       sudo apt-get update -y ;
       sudo apt install adoptopenjdk-8-hotspot -y ;
       sudo apt remove adoptopenjdk-11-hotspot -y ;
       java -version ;
     fi

script :
    -  ./gradlew build 
    -  ./gradlew clean test  --rerun-tasks 
