# ----------------------------------------------------------------------------
#
# Package             : okhttp
# Source Repo         : https://github.com/square/okhttp
# Travis Job Link     : https://travis-ci.com/github/asellappen/okhttp/
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
dist: xenial

language: java

jdk: openjdk11

matrix:
  include:
  # - arch: amd64 
  #   os: linux
  #   dist: xenial

   - arch: ppc64le 
     os: linux
     dist: bionic

before_install:
   - npm install --save-dev jetifier
   - npx jetify

script :
#samples:guide:compileJava not supported for ppc64le
   - if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then 
      ./gradlew build  -x  "samples:guide:compileJava" ;
      ./gradlew clean test  -x  "samples:guide:compileJava"  --rerun-tasks;
     else
      ./gradlew build  ;
      ./gradlew clean test  --rerun-tasks ;
     fi
